import DateWeather from '../@types/DateWeather'

interface CreateWeatherContentProps {
  dateWeathers: DateWeather[]
}

export default function createWeatherContent (props: CreateWeatherContentProps): string {
  const {
    dateWeathers
  } = props

  const header = '🌤️ 今後の天気予報 🌧️'

  const weatherContent = dateWeathers.map(dateWeather => {
    return `📅 ${dateWeather.date} ${dateWeather.weather.emoji} (${dateWeather.weather.description})`
  }).join('\n')

  const footer = 'Powered by Open-Meteo (generated by Google Apps Script automatically. do not edit this message)'

  return [header, '', weatherContent, '', footer].join('\n')
}
